# Numpy

## Installation et import

Installer numpy via le gestionnaire de dépendance pip grâce à la commande :

pip install numpy

Import de numpy dans un fichier

In [5]:
import numpy as np

## Description

numpy est une librairie optimisée pour le calcul mathématique

# Création d'objets numpy

In [7]:
np.array([0, 1, 2, 3])

array([0, 1, 2, 3])

In [8]:
np.arange(4)

array([0, 1, 2, 3])

In [9]:
np.arange(2*3*4).reshape(2, 3, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [10]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Shapes

In [20]:
np.eye(5).shape

(5, 5)

In [21]:
np.arange(4).shape

(4,)

## Opération entre les objets numpy

In [13]:
np.zeros((5,5)) + 1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.eye(5) + np.arange(5*5).reshape(5, 5)

array([[ 1.,  1.,  2.,  3.,  4.],
       [ 5.,  7.,  7.,  8.,  9.],
       [10., 11., 13., 13., 14.],
       [15., 16., 17., 19., 19.],
       [20., 21., 22., 23., 25.]])

In [15]:
np.eye(5) * np.arange(5*5).reshape(5, 5)

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  6.,  0.,  0.,  0.],
       [ 0.,  0., 12.,  0.,  0.],
       [ 0.,  0.,  0., 18.,  0.],
       [ 0.,  0.,  0.,  0., 24.]])

Multiplication matricielle

In [16]:
np.dot(np.eye(5), np.arange(5*5).reshape(5, 5))

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

## Obtention d'éléments

L'obtention d'éléments fonctionne de manière analogue à l'obtention d'éléments pour les listes

In [6]:
arr = np.arange(2*3*4).reshape(2, 3, 4)

In [7]:
arr[:,1:-1,0]

array([[ 4],
       [16]])

## Algèbre linéaire

numpy possède un package d'algèbre linéaire np.linalg

Exemple avec l'inversion de matrice

In [22]:
np.linalg.inv(np.arange(4).reshape((2,2)))

array([[-1.5,  0.5],
       [ 1. ,  0. ]])